#!/bin/sh
#
# Start overlay
#

start() {

	# Get the rw up in place
	mount -o noatime -t ubifs ubi0:rootfs_data /overlay

	# Get the overlay running
	mkdir -m 0755 -p /overlay/upper
	mkdir -m 0755 -p /overlay/work
	mount -o noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work -t overlay overlayfs:/overlay /mnt

	# Finally pivot the system
	mount -o noatime,move /proc /mnt/proc
	pivot_root /mnt /mnt/rom
	mount -o noatime,move /rom/sys /sys
	mount -o noatime,move /rom/dev /dev
	mount -o noatime,move /rom/tmp /tmp
	mount -o noatime,move /rom/run /run
	mount -o noatime,move /rom/overlay /overlay

	echo "OK"
}

stop() {
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
